name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        arch: [x64]
        mode: [debug, release]
        include:
          - os: windows-latest
            arch: x86
            mode: debug
          - os: windows-latest
            arch: x86
            mode: release
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
      with:
        arch: ${{ matrix.arch }}
    - run: luamake -mode ${{ matrix.mode }}
